version: '3.9'
services:
    dumbpad:
        image: dumbwareio/dumbpad:latest
        ports:
            - "7676:3000"
        volumes:
            - "${APP_DATA_DIR}/data:/app/data"
        environment:
            - DUMBPAD_PIN=${DUMBPAD_PIN:-123456}
