version: '3.9'
services:
  app_proxy:
    environment:
      APP_HOST: marcias-dumbpad_web_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"  # Brak wymuszenia logowania przez Umbrel

  web:
    image: dumbwareio/dumbpad:latest
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    environment:
      - DUMBPAD_PIN=${DUMBPAD_PIN:-}
    entrypoint: |
      sh -c '
        mkdir -p /app/data
        if [ ! -f /app/data/notepads.json ]; then
          echo "[]" > /app/data/notepads.json
        fi
        exec npm start
      '
