version: '3.9'

services:
  app_proxy:
    environment:
      APP_HOST: marcias-dumbpad_web_1
      APP_PORT: 3000

  web:
    image: dumbwareio/dumbpad:latest
    restart: on-failure
    user: "1000:1000"
    volumes:
      - "${APP_DATA_DIR}/data:/app/data"
    environment:
      - PUID=1000
      - PGID=1000  
      - DUMBPAD_PIN=${DUMBPAD_PIN:-}
          
