version: '3.9'

services:
  app_proxy:
    environment:
      APP_HOST: marcias-dumbpad_web_1
      APP_PORT: 3000

  web:
    image: dumbwareio/dumbpad:latest
    restart: on-failure
    volumes:
      - "${APP_DATA_DIR}/data:/app/data"
    environment:
      - DUMBPAD_PIN=${DUMBPAD_PIN:-}
    command: sh -c "mkdir -p /app/data && chmod 777 /app/data && npm start"
          
